name: "NISTtheDocs2Death"

on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: usnistgov/sphinx-action@0.5
        with:
          docs-folder: docs/
      - uses: usnistgov/sphinx-action@0.5
        with:
          docs-folder: docs/
          build-command: make latexpdf
      - uses: usnistgov/sphinx-action@0.5
        with:
          docs-folder: docs/
          build-command: make epub
      - uses: usnistgov/NISTtheDocs2Death@main
        with:
          docs-folder: docs/
      - uses: actions/upload-artifact@v1
           with:
             name: DocumentationPDF
             path: docs/_build/pdf/
      - uses: actions/upload-artifact@v1
           with:
             name: DocumentationEPUB
             path: docs/_build/epub/
