name: "NISTtheDocs2Death"

on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: usnistgov/sphinx-action@0.5
        with:
          docs-folder: "docs/"
